### ISSUE TITLE
[Feature] The save and load methods for tensor

### ISSUE THREAD

**Issue by Final-Saber** [SciSharp/Tensor.NET#3]
Hi, I was finding a way to save and load a tensor with ```Tensor.NET```. I found two static classes ```TensorWriter``` and ```TensorReader```. However, maybe some apis like ```Tensor.Load()``` and ```Tensor.Save``` to directly be called from a tensor instance will make it more convinience.

**Comment by AsakusaRinne** [comment]
There has already been a ```Tensor<T>.Save``` method now. I guess you tried to use ```Tensor.Save``` so that you didn't find it. 

I will add ```Tensor.Save``` and ```Tensor.Load``` soon. Thank you for your advise!
