### ISSUE TITLE
[Feature] The support for .npy format

### ISSUE THREAD

**Issue by Final-Saber** [SciSharp/Tensor.NET#4]
Currently, the library seems to have its own way to serialize the tensor. Will the library support the saving and loading of the ```.npy``` format? I would like to submit a PR about when I get time.

**Comment by AsakusaRinne** [comment]
Yes, the support for ```.npy``` file will be added in the future, since many people may need to transfer from Numpy and Python.

I will appreciate it if you would like to help complete this feature!
